// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/AdminLayout.vue')['default']
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    Button: typeof import('./src/components/button/index.vue')['default']
    CircleBtn: typeof import('./src/components/button/circleBtn.vue')['default']
    CollectionLayout: typeof import('./src/components/CollectionLayout.vue')['default']
    Confirm: typeof import('./src/components/confirm/index.vue')['default']
    HomeLayout: typeof import('./src/components/HomeLayout.vue')['default']
    MoveStar: typeof import('./src/components/MoveStar.vue')['default']
    NormalBtn: typeof import('./src/components/button/normalBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
